/** @format */

export const actionsTypes = {
  PULL_DECKS: "PULL_DECKS",
  PULL_CARD: "PULL_CARD",
  RESTART_SETTINGS: "RESTART_SETTINGS",
  ADD_TO_ROUNDS_HISTORY: " ADD_TO_ROUNDS_HISTORY",
  BID_BET: "BID_BET",
  PULL_CARD_FOR_CROUPIER: "PULL_CARD_FOR_CROUPIER",
};
